[package]
name = "mint_nft"
edition = "2024.beta" 

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet" }

[addresses]
mint_nft = "0x0"

[dev-dependencies]

[dev-addresses]